@baseUrl = http://localhost:3000/api/v1
@email = charles@gmail.com
@password = Qwerty123

### Inscription valide
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "pseudonyme": "Charles"
}

### Inscription invalide - validation Zod
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "in-co-rect",
  "password": "qwerty",
  "pseudonyme": "Charles"
}


### Login valide (attribue le nom login a cette requetes pour chercher les tokens directement par la suite)
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Access/Refresh token ajouter automatiquement
@accessToken = {{login.response.body.$.accessToken}}
@refreshToken = {{login.response.body.$.refreshToken}}

### Login invalide
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "Mauvais123"
}

### Me avec access token
GET {{baseUrl}}/auth/me
Authorization: Bearer {{accessToken}}

### Me sans token
GET {{baseUrl}}/auth/me

### Refresh invalide - body vide
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": ""
}

### Refresh invalide - faux JWT
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "test"
}

### Refresh valide
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### Logout valide
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### Refresh après logout
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### Créer une entrée journal
POST {{baseUrl}}/journal
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "date": "2026-09-15",
  "humeur": 4,
  "energie": 3,
  "qualite_sommeil": 4,
  "anxiete_stress": 2,
  "evenements": "EVENEMENT TEST",
  "gratitude": "GRATITUDE TEST"
}

### Liste des activités  (public)
GET {{baseUrl}}/activities

### Journal avec activités
POST {{baseUrl}}/journal
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "date": "2026-05-02",
  "humeur": 4,
  "energie": 4,
  "qualite_sommeil": 3,
  "anxiete_stress": 2,
  "evenements": "TEST EVENEMENT",
  "gratitude": "TEST GRATITUDE",
  "activityIds": [
    "cmsv2spie0000zwv5smr56be6",
    "cmsv2spif0003zwv5c34e5v3i"
  ]
}

### Liste du journal - page 1
GET {{baseUrl}}/journal?page=1&limit=20
Authorization: Bearer {{accessToken}}

### Liste du journal - page 2
GET {{baseUrl}}/journal?page=2&limit=20
Authorization: Bearer {{accessToken}}

### Journal par date
GET {{baseUrl}}/journal/date?date=2026-05-02
Authorization: Bearer {{accessToken}}

### Journal date invalide
GET {{baseUrl}}/journal/date?date=allo
Authorization: Bearer {{accessToken}}